import './charityData.js';
import './bookAPI.js';
import './viewSwitcher.js';
import './fetchCategories.js';
import './fetchBooks.js';
import './fetchBooksByCategories.js';
import './shoppingList.js';
import './mobileMenu.js';
import './scrollUp.js';
